### ISSUE TITLE
Peer to peer code review to Desmond by Rex, T-Kay and Mark

### ISSUE THREAD

**Issue by HtetNaing0814** [Owusu-Desmond/portfolio#10]
Code review by Rex, T-Kay and Mark

**Comment by MxoDevops** [comment]
#ReadMe page on Acknowledgments 
Thank Microverse for the template and the readme template.

**Comment by HtetNaing0814** [comment]
It should follow naming conventions for CSS-style classes.
It should be "bullet" before Editor: VScode instead of "-".
Image should be from figma for more precision to the template.

**Comment by Markotweyo** [comment]
-Great SVG files for responsive design
